name: cosdart
description: Contentos blockchain SDK for Dart.
version: 0.2.1
homepage: https://github.com/coschain/cosdart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  protobuf: "^1.0.1"
  grpc: "^2.1.3"
  fixnum: "^0.10.11"
  crclib: "^1.0.1"

dev_dependencies:
  test: "^1.11.0"
